module.exports = {
	playlistUpdateExternal: require('./playlistUpdateExternal'),
	updatePlaylistImage: require('./updatePlaylistImage'),
	fanPlaylistProgress: require('./fanPlaylistProgress'),
	generateSchoolCode: require('./generateSchoolCode'),
	fanPlaylistToUser: require('./fanPlaylistToUser'),
	generateClassCode: require('./generateClassCode'),
	createGameImage: require('./createGameImage'),
	updateSavedMeta: require('./updateSavedMeta'),
	solutionChecker: require('./solutionChecker'),
	assignPlaylists: require('./assignPlaylists'),
	updateGameMeta: require('./updateGameMeta'),
	fanDraftToUser: require('./fanDraftToUser'),
	returnPlaylist: require('./returnPlaylist'),
	fanCompleted: require('./fanCompleted'),
	copyPlaylist: require('./copyPlaylist'),
	createGif: require('./createGif'),
	// updateSavedImage: require('./updateSavedImage'),
	// toggleShowcase: require('./toggleShowcase'),
	// fanGameToUser: require('./fanGameToUser'),
	// autoYield: require('./autoYield')
}
