module.exports = {
  playlistUpdateExternal: require('./playlistUpdateExternal'),
  updatePlaylistImage: require('./updatePlaylistImage'),
  fanPlaylistProgress: require('./fanPlaylistProgress'),
  assignRecentOnJoin: require('./assignRecentOnJoin'),
  generateSchoolCode: require('./generateSchoolCode'),
  fanPlaylistToUser: require('./fanPlaylistToUser'),
  generateClassCode: require('./generateClassCode'),
  createGameImage: require('./createGameImage'),
  updateSavedMeta: require('./updateSavedMeta'),
  solutionChecker: require('./solutionChecker'),
  assignPlaylists: require('./assignPlaylists'),
  updateGameMeta: require('./updateGameMeta'),
  fanDraftToUser: require('./fanDraftToUser'),
  checkUserEmail: require('./checkUserEmail'),
  returnPlaylist: require('./returnPlaylist'),
  pinAssignment: require('./pinAssignment'),
  createNewUser: require('./createNewUser'),
  fanCompleted: require('./fanCompleted'),
  copyPlaylist: require('./copyPlaylist'),
  createGif: require('./createGif'),
  weoAuth: require('./weoAuth'),
  api: require('./api')
}
